[[bookmark]]
key = "v"
path = "/Users/windus/izone/volume"

[[bookmark]]
key = "j"
path = "/Users/windus/izone/code/java"

[[bookmark]]
key = "c"
path = "/Users/windus/izone/code"

[[bookmark]]
key = "g"
path = "/Users/windus/izone/code/github"

[[bookmark]]
key = "s"
path = "/Users/windus/izone/shell"
